name = "macroecoai"
main = "src/worker.js"
compatibility_date = "2024-06-22"

[triggers]
crons = ["0 0 * * 1"]

[[d1_databases]]
binding = "DB"
database_name = "macroecoai-db"
database_id = "placeholder-db-id"

[[kv_namespaces]]
binding = "CACHE"
id = "placeholder-kv-id"

[vars]
ENVIRONMENT = "production"

[env.production.vars]
NEWS_API_KEY = "your-newsapi-key"

# Local development environment
[env.local]
[[env.local.d1_databases]]
binding = "DB"
database_name = "macroecoai-db-local"
database_id = "placeholder-local-db-id"

[[env.local.kv_namespaces]]
binding = "CACHE" 
id = "placeholder-local-kv-id"

[env.local.vars]
ENVIRONMENT = "local"
